version: '3.8'

services:
  falcon_api:
    container_name: falcon_api
    build: ./app
    volumes:
      - type: bind
        source: ./app
        target: /app
    user: root  # Ajout de l'option user: root pour le service falcon_api
    expose:
      - 8090
    ports:
      - 8000:80
      - 80:8000
    working_dir: /app/ipl_api
    command: gunicorn --reload ipl_api.app --bind 0.0.0.0:8000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    user: root
    build: db/
    container_name: db
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=falcon_bdd
    healthcheck:
      test: "exit 0"

volumes:
  data-volume:
